service: the-song-is-service

provider:
  name: aws
  runtime: java8

package:
  artifact: target/the-song-is-function-1.0.jar

functions:
  hello:
    handler: io.confluent.demos.thesongis.TheSongIsStreamHandler
    environment:
      REDIS_HOST: ${redis_host}
      REDIS_PORT: ${redis_port}
    events:
      - alexaSkill: ${alexa_skill_id}
    vpc:
      securityGroupIds:
        - ${security_group_id}
      subnetIds:
        - ${private_subnet_0}
        - ${private_subnet_1}
        - ${private_subnet_2}
